version: "3.8-alpine"

services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - DOCKER=True
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=boardgames_dev
  boardgames:
    build:
      context: ./
    ports:
      - 5000:5000
    env_file:
      - ./.env
